version: '3.8'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/:/config/
    devices:
      - /dev/usb_dsmr:/dev/usb_dsmr
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.homeassistant.rule=Host(`${DASHBOARD_URL}`)
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=letsencrypt
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
    networks:
      - traefik
      - influxdb
      - transmission
    restart: unless-stopped

networks:
  traefik:
    external: true
  influxdb:
    external: true
  transmission:
    external: true
